services:
  uptime-kuma:
    container-name: uptime-kuma
    image: louislam/uptime-kuma:2.1.3
    restart: unless-stopped
    volumes:
      - ${APPDATA_LOCATION}/uptime-kuma:/app/data
    ports:
      - "3001:3001"