services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command: serve
    environment:
      - TZ=Europe/London
    volumes:
      - ${APPDATA_LOCATION}/ntfy/cache:/var/cache/ntfy
      - ${APPDATA_LOCATION}/ntfy/config:/etc/ntfy
    ports:
      - 3017:80
    restart: always
